version: 2

sources:
  - name: silver
    schema: silver
    tables:
      - name: click_stream
        description: "Raw clickstream event logs from users interacting with the website or app."
        columns:
          - name: user_id
            description: "Unique identifier for the user who triggered the event."
          - name: event_type
            description: "Type of event, such as page_view or add_to_cart."
          - name: product_id
            description: "Product involved in the event."
          - name: session_id
            description: "Unique session ID grouping related events."
          - name: event_date
            description: "Date of the event (YYYY-MM-DD)."

      - name: customers
        description: "Customer master data including signup info and demographics."
        columns:
          - name: customer_id
            description: "Unique identifier for each customer."
          - name: email
            description: "Customer's email address."
          - name: country
            description: "Country provided at signup."

      - name: purchases
        description: "Records of purchase transactions completed by users."
        columns:
          - name: order_id
            description: "Unique identifier for each order."
          - name: user_id
            description: "User ID associated with the purchase."
          - name: product_id
            description: "Product purchased."
          - name: total_amount
            description: "Total monetary value of the order."

models:
  - name: stg_clickstream
    description: "Staging model that cleans and renames raw clickstream data."
    columns:
      - name: user_id
        description: "Unique identifier of the user."
        tests:
          - not_null
      - name: event_timestamp
        description: "Timestamp when the event occurred."
        tests:
          - not_null
      - name: event_type
        description: "The kind of event (e.g. page_view, add_to_cart)."
      - name: product_id
        description: "Product referenced in the event, if applicable."
      - name: session_id
        description: "Session grouping ID."
      - name: data_source
        description: "Source of data ingestion."

  - name: stg_customers
    description: "Staging model that standardizes raw customer data for analysis."
    columns:
      - name: customer_id
        description: "Unique identifier of the customer."
        tests:
          - not_null
          - unique
      - name: full_name
        description: "Full name of the customer."
      - name: email
        description: "Customer's email address."
      - name: email_domain
        description: "Extracted domain from the customer's email address."
      - name: country
        description: "Country of the customer."
      - name: signup_date
        description: "The date when the customer signed up."
        tests:
          - not_null

  - name: stg_purchases
    description: "Staging model that cleans and enriches raw purchase data."
    columns:
      - name: order_id
        description: "Unique order ID."
        tests:
          - not_null
          - unique
      - name: user_id
        description: "User who made the purchase."
        tests:
          - not_null
          - relationships:
              to: ref('stg_clickstream')
              field: user_id
      - name: product_id
        description: "Product that was purchased."
      - name: purchase_timestamp
        description: "Timestamp of the purchase event."
        tests:
          - not_null
      - name: quantity
        description: "Quantity of product purchased."
        tests:
          - not_null
      - name: unit_price
        description: "Price per unit of the product."
        tests:
          - not_null
      - name: total_amount
        description: "Total amount for the purchase = unit_price * quantity."
        tests:
          - not_null
          - expression_is_true:
              sql: "total_amount >= 0"
